### PR TITLE
remove 1.1

### PR DESCRIPTION
**Pull request by mprorock**
Leave 1.1 vc-jwt items to the 1.1 spec, let's keep this focused on version 2.0+

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jwt/pull/85.html" title="Last updated on May 16, 2023, 3:55 PM UTC (ccad3c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jwt/85/0b73db0...ccad3c4.html" title="Last updated on May 16, 2023, 3:55 PM UTC (ccad3c4)">Diff</a>

### CODE REVIEW

**Comment by OR13** [comment]
I raised the same PR, at the same time... on the same call... https://github.com/w3c/vc-jwt/pull/87

**Review by andresuribe87 — APPROVED** [review]

**Review by selfissued — APPROVED** [review]
This will simplify our work.

**Review by brentzundel — APPROVED** [review]

**Review by decentralgabe — APPROVED** [review]

**Review by msporny — APPROVED** [review]

**Review by awoie — APPROVED** [review]
lgtm

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-05-24-vcwg#section1-2) on 2023-05-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. remove 1.1  (pr vc-jwt#85)

_See github pull request [vc-jwt#85](https://github.com/w3c/vc-jwt/pull/85)._




> *Orie Steele:* This PR should be merged: [https://github.com/w3c/vc-status-list-2021/pull/46](https://github.com/w3c/vc-status-list-2021/pull/46).

**Michael Prorock:** It has all approvals in -- just want to make sure there are no additional commentaries in there before it goes in.  

**Kristina Yasuda:** I see 6 approvals and 1 week time. Why is it not merged yet?  

**Michael Prorock:** Just hit a week now.  

**Kristina Yasuda:** Any objections on this call now?  

</details>

**Comment by umukoroejayeta** [comment]
Review

**Pull request merged**
